# -*- coding: utf-8 -*-
"""zahara hayati

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GLV37zDMxLs-mooMwupeZ7nDp6De3M7n
"""

# Toko Online Sederhana

produk = {
    1: {"nama": "Kaos Polos", "harga": 50000},
    2: {"nama": "Celana Jeans", "harga": 120000},
    3: {"nama": "Jaket Hoodie", "harga": 150000},
    4: {"nama": "Topi Snapback", "harga": 40000}
}
'''daftar barang yang dijual di toko'''

keranjang = []
'''tempat menyimpan barang pembelanjaan pembeli'''

def tampilkan_produk():
    print("\n=== Daftar Produk ===")
    for kode, info in produk.items():
        print(f"{kode}. {info['nama']} - Rp{info['harga']:,}")
'''Ini buat nampilin semua produk yang ada.
Pakai for untuk ngeloop semua barang, lalu ditampilkan lengkap dengan harga'''


def tambah_ke_keranjang():
    try:
        kode = int(input("Masukkan kode produk yang ingin dibeli: "))
        if kode in produk:
            keranjang.append(produk[kode])
            print(f"{produk[kode]['nama']} berhasil ditambahkan ke keranjang.")
        else:
            print("Kode produk tidak ditemukan.")
    except ValueError:
        print("Masukkan angka yang valid.")
        '''Di bagian ini, user bisa pilih barang yang mau dibeli.
user diminta masukin kode barang.
Kalau kodenya benar, barang masuk ke keranjang.
Kalau salah, muncul pesan.
Kalau user ketik huruf atau simbol, akan dicegah pakai try-except''''

def lihat_keranjang():
    print("\n=== Isi Keranjang ===")
    if not keranjang:
        print("Keranjang kosong.")
    else:
        total = 0
        for i, item in enumerate(keranjang, 1):
            print(f"{i}. {item['nama']} - Rp{item['harga']:,}")
            total += item['harga']
        print(f"Total sementara: Rp{total:,}")
'''Di sini kita bisa lihat isi keranjang.
Kalau kosong, muncul pesan.
Kalau ada isinya, ditampilkan satu-satu + total harga semua belanjaan'''

def checkout():
    if not keranjang:
        print("Keranjang masih kosong. Tidak bisa checkout.")
        return
    lihat_keranjang()
    konfirmasi = input("Lanjut ke checkout? (y/n): ")
    if konfirmasi.lower() == 'y':
        print("Terima kasih sudah berbelanja!")
        keranjang.clear()
    else:
        print("Checkout dibatalkan.")
'''ini user bisa selesaikan belanja (checkout).
Dicek dulu apakah keranjang ada isinya.
Kalau kosong, nggak bisa lanjut.
Kalau ada, ditanya dulu yakin atau nggak.
Kalau “y”, keranjang dikosongkan (transaksi selesai).
Kalau “n”, dibatalkan'''

def menu():
    while True:
        print("\n=== TOKO ONLINE SEDERHANA ===")
        print("1. Lihat Produk")
        print("2. Tambah ke Keranjang")
        print("3. Lihat Keranjang")
        print("4. Checkout")
        print("5. Keluar")
        pilihan = input("Pilih menu (1-5): ")

        if pilihan == '1':
            tampilkan_produk()
        elif pilihan == '2':
            tampilkan_produk()
            tambah_ke_keranjang()
        elif pilihan == '3':
            lihat_keranjang()
        elif pilihan == '4':
            checkout()
        elif pilihan == '5':
            print("Terima kasih telah mengunjungi toko kami!")
            break
        else:
            print("Pilihan tidak valid. Silakan coba lagi.")
'''bagian utama program.
Menu terus muncul selama program berjalan.
User bisa pilih 1–5 buat akses fitur.
Kalau pilih 5, program akan berhenti (keluar)'''

# Jalankan program
menu()
'''bagian terakhir.
Kalau file dijalankan, fungsi menu() langsung aktif, dan program mulai berjalan'''